### ISSUE TITLE
When using it with `@typescript-eslint/consistent-type-exports`

### ISSUE THREAD

**Issue by CMCDragonkai** [ota-meshi/eslint-plugin-jsonc#201]
I get an error when integrating this plugin while also using `@typescript-eslint/consistent-type-exports`.

Here's an extract out of my `.eslintrc`:

```
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "tsconfig.json",
    "sourceType": "module"
  },
  "overrides": [
    {
      "files": ["*.json", "*.jsonc", "*.json5"],
      "parser": "jsonc-eslint-parser"
    }
  ],
  "plugins": [
    "import"
  ],
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:prettier/recommended",
    "plugin:jsonc/recommended-with-json",
    "prettier"
  ],
```

Upon using this, I end up with:

```
Oops! Something went wrong! :(

ESLint: 8.17.0

Error: Error while loading rule '@typescript-eslint/consistent-type-exports': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Occurred while linting /home/cmcdragonkai/Projects/Polykey/src/tokens/schemas/TokenHeaderSignatureSchema.json
    at Object.getParserServices (/home/cmcdragonkai/Projects/Polykey/node_modules/@typescript-eslint/utils/dist/eslint-utils/getParserServices.js:15:15)
    at create (/home/cmcdragonkai/Projects/Polykey/node_modules/@typescript-eslint/eslint-plugin/dist/rules/consistent-type-exports.js:64:37)
    at Object.create (/home/cmcdragonkai/Projects/Polykey/node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:41:20)
    at createRuleListeners (/home/cmcdragonkai/Projects/Polykey/node_modules/eslint/lib/linter/linter.js:922:21)
    at /home/cmcdragonkai/Projects/Polykey/node_modules/eslint/lib/linter/linter.js:1104:31
    at Array.forEach (<anonymous>)
    at runRules (/home/cmcdragonkai/Projects/Polykey/node_modules/eslint/lib/linter/linter.js:1041:34)
    at Linter._verifyWithoutProcessors (/home/cmcdragonkai/Projects/Polykey/node_modules/eslint/lib/linter/linter.js:1389:31)
    at Linter._verifyWithConfigArray (/home/cmcdragonkai/Projects/Polykey/node_modules/eslint/lib/linter/linter.js:1729:21)
    at Linter.verify (/home/cmcdragonkai/Projects/Polykey/node_modules/eslint/lib/linter/linter.js:1471:65)
```

If I remove this plugin, things work again.

It seems the addition of the `overrides` ends up causing that above problem.

**Comment by ota-meshi** [comment]
Cannot use `@typescript-eslint/*` rules in JSON files.
You need to use `overrides` section to configure those rules to be turned off in `*.json` files.
Or you need to use `overrides` section to configure `@typescript-eslint/*` rules to apply only to `*.ts` files.
